# -------------------------------------- #
# --- VARIABLE FOR BUILDARCHITECTURE --- #
# ---------------------------------------#
BUILDARCH = i686 

###Recipes:
headers:
	cd $(BUILDARCH) && $(MAKE) headers

objfiles:
	cd $(BUILDARCH) && $(MAKE) objfiles

clean:
	cd $(BUILDARCH) && $(MAKE) clean
