###Recipes:
headers:
	cd tty && $(MAKE) headers
	cd keyboard && $(MAKE) headers

objfiles:
	cd tty && $(MAKE) objfiles
	cd keyboard && $(MAKE) objfiles
	
clean: tty/Makefile
	cd tty && $(MAKE) clean
	cd keyboard && $(MAKE) clean
	
